version: '3.4'

services:
  app:
    container_name: couch-potato-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}"

  db:
    image: postgres:13-alpine
    container_name: couch-potato-db
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}

volumes:
  gem_cache:
  db_data:
  node_modules:
